# Generated by Django 5.2.9 on 2025-12-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0003_update_max_dte_to_50"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="is_automated_entry",
            field=models.BooleanField(
                default=False,
                help_text="Whether position was opened by automated trading (vs manual)",
            ),
        ),
    ]
