# Generated by Django 5.2.8 on 2025-11-25 19:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OptionsAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_method', models.CharField(choices=[('conservative', 'Conservative (40% Risk Tolerance)'), ('moderate', 'Moderate (50% Risk Tolerance)'), ('aggressive', 'Aggressive (60% Risk Tolerance)'), ('user_defined', 'User Defined Risk Tolerance')], default='conservative', max_length=20)),
                ('risk_tolerance', models.FloatField(default=0.4, help_text='Normal market risk tolerance (0.01-0.80)', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(0.8)])),
                ('stressed_risk_tolerance', models.FloatField(default=0.6, help_text='Stressed market risk tolerance (0.01-0.80)', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(0.8)])),
                ('warning_threshold_high', models.FloatField(default=0.8, help_text='High warning threshold for risk utilization (0.50-0.95)', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(0.95)])),
                ('warning_threshold_medium', models.FloatField(default=0.65, help_text='Medium warning threshold for risk utilization (0.40-0.90)', validators=[django.core.validators.MinValueValidator(0.4), django.core.validators.MaxValueValidator(0.9)])),
                ('strategy_power', models.DecimalField(decimal_places=2, default=0, help_text='Risk Budget: Risk Tolerance × Tradeable Capital', max_digits=15)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='options_allocation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('TASTYTRADE', 'TastyTrade')], default='TASTYTRADE', max_length=20)),
                ('account_number', models.CharField(max_length=50)),
                ('account_nickname', models.CharField(blank=True, max_length=100)),
                ('access_token', encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ('refresh_token', encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ('token_type', models.CharField(blank=True, max_length=20)),
                ('scope', models.CharField(blank=True, max_length=200)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_test', models.BooleanField(default=False, help_text='Use TastyTrade sandbox environment instead of production. Requires separate OAuth credentials for sandbox accounts. All orders are executed normally in the selected environment.')),
                ('is_token_valid', models.BooleanField(default=True, help_text='Whether refresh token is valid - False means user needs to re-authenticate')),
                ('last_authenticated', models.DateTimeField(blank=True, null=True)),
                ('token_refresh_count', models.IntegerField(default=0)),
                ('last_token_rotation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradingAccountPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_automated_trading_enabled', models.BooleanField(default=False, help_text='Enable daily automated trading for this account (executes 30 min after market open)')),
                ('automated_entry_offset_cents', models.PositiveIntegerField(default=0, help_text='Limit price offset (in cents) when automation submits credit trades')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_preferences', to='accounts.tradingaccount')),
            ],
            options={
                'verbose_name': 'Trading Account Preferences',
                'verbose_name_plural': 'Trading Account Preferences',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_preference', models.CharField(choices=[('none', 'No Emails'), ('immediate', 'Emails for All Activity'), ('summary', 'Summary Email End of Day')], default='summary', help_text='Email notification preference for trading activity', max_length=20)),
                ('email_daily_trade_suggestion', models.BooleanField(default=False, help_text='Send daily trade suggestion email at 10:00 AM ET (market open)')),
                ('privacy_mode', models.BooleanField(default=False, help_text='Hide account balance on dashboard when enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='AccountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('buying_power', models.DecimalField(decimal_places=2, help_text='Available buying power', max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Total account balance', max_digits=15)),
                ('source', models.CharField(choices=[('stream', 'Real-time stream'), ('sdk', 'Direct SDK call'), ('manual', 'Manual entry')], default='sdk', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'account_number', '-created_at'], name='accounts_ac_user_id_9cb1ec_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tradingaccount',
            index=models.Index(fields=['user', 'is_primary'], name='accounts_tr_user_id_60e36f_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingaccount',
            index=models.Index(fields=['user', 'is_active'], name='accounts_tr_user_id_7c1b3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tradingaccount',
            unique_together={('user', 'account_number', 'connection_type')},
        ),
    ]
