# Generated by Django 5.2.8 on 2025-12-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_unused_oauth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccountpreferences',
            name='auto_profit_targets_enabled',
            field=models.BooleanField(default=True, help_text='Automatically create profit target orders when spread positions open. Does not affect Senex Trident which always uses its own algorithm.'),
        ),
    ]
